---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/hmariset/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-fix/KONFLUX-14438-add-push-label-filter
