---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/hmariset/infra-deployments.git
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-add-prod-provider-config
