resources:
- ../base
- https://github.com/konflux-ci/crossplane-control-plane/examples/provider-kubernetes-in-cluster?ref=f61fa6c74ed6e7ac1a913c35612498157b37549d

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
